/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bookmanagement.view;

/**
 *
 * @author ADMIN
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class BookManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookPanel
     */
    
    public BookManagementPanel() {
        initComponents();
        initTable();
    }
    
    public void initTable(){
        DefaultTableModel tableModel = new DefaultTableModel(
            new Object[]{"ID BOOK", "AUTHOR", "BOOK NAME", "KIND", "DESCRIPT", "PRICE"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblBang.setModel(tableModel);
    }
    
    public void addBook(){
        BookEntryDialog dialog = new BookEntryDialog(null, true, null); // true: modal, null: không có dữ liệu để chỉnh sửa
        dialog.setVisible(true); // Hiển thị dialog

        // Kiểm tra kết quả sau khi dialog đóng
        if (dialog.isDataSaved()) {
            JOptionPane.showMessageDialog(this, "Thêm sách mới thành công!");
             // Tải lại dữ liệu vào bảng để hiển thị sách mới
        }
    }
    
    public void deleteBook(){
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnToolbar = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JToggleButton();
        btnSua = new javax.swing.JToggleButton();
        btnXoa = new javax.swing.JToggleButton();
        btnLamMoi = new javax.swing.JToggleButton();
        tblBook = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblSearch.setText("Search: ");
        pnToolbar.add(lblSearch);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        pnToolbar.add(txtSearch);

        btnTimKiem.setText("Tìm KIếm");
        pnToolbar.add(btnTimKiem);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnToolbar.add(jSeparator1);

        btnThem.setText("Thêm");
        pnToolbar.add(btnThem);

        btnSua.setText("Sửa");
        pnToolbar.add(btnSua);

        btnXoa.setText("Xóa");
        pnToolbar.add(btnXoa);

        btnLamMoi.setText("Làm Mới");
        pnToolbar.add(btnLamMoi);

        add(pnToolbar, java.awt.BorderLayout.PAGE_START);

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        tblBook.setViewportView(tblBang);

        add(tblBook, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        // TODO add your handling code here:
        if(tblBang.getSelectedRow() != -1){
            btnXoa.setEnabled(true);
            btnSua.setEnabled(true);
        }
        else{
            btnXoa.setEnabled(false);
            btnSua.setEnabled(false);
        }
    }//GEN-LAST:event_tblBangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLamMoi;
    private javax.swing.JToggleButton btnSua;
    private javax.swing.JToggleButton btnThem;
    private javax.swing.JToggleButton btnTimKiem;
    private javax.swing.JToggleButton btnXoa;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel pnToolbar;
    private javax.swing.JTable tblBang;
    private javax.swing.JScrollPane tblBook;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
