/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookmanagement.view;

import java.awt.CardLayout;

/**
 *
 * @author ADMIN
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Interface
     */
    
    private CardLayout cards;
    private HomePanel homePanel;
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1200, 700);
        
        cards = (CardLayout) containerPanel.getLayout();
        
        // Khởi tạo homePanel TRƯỚC khi tạo LoginPanel
        homePanel  = new HomePanel(this); 
        System.out.println("HomePanel created. HomePanel hash: " + homePanel.hashCode());

        LoginPanel login = new LoginPanel(this); // LoginPanel giờ đây nhận một MainFrame đã có homePanel
        System.out.println("LoginPanel created.");

        // Thêm vào card stack
        containerPanel.add(login, "LOGIN");
        containerPanel.add(homePanel,  "HOME"); // Sử dụng biến thành viên
        System.out.println("Panels added to container.");

        // Hiển thị login trước
        cards.show(containerPanel, "LOGIN");
        System.out.println("Showing LOGIN panel.");
    }
  
    public void showHome() {
        cards.show(containerPanel, "HOME");
    }
    
    public void showLogin(){
        cards.show(containerPanel, "LOGIN");
    }
    
    public HomePanel getHomePanel() {
        return homePanel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        containerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOK MANAGEMENT");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(800, 500));

        containerPanel.setBackground(new java.awt.Color(102, 102, 102));
        containerPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(containerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    // End of variables declaration//GEN-END:variables

}
