/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookmanagement.view;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Main_Interface extends javax.swing.JFrame {
    
    /**
     * Creates new form Main_Interface
     */
    public Main_Interface() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1000, 700);
        
        CardLayout cardLayout = (CardLayout) mainContentPanel.getLayout();

        // 2. Thêm các Panel chức năng vào mainContentPane
        // Mỗi màn hình chức năng sẽ là một thể hiện của JPanel Form bạn tạo riêng
        mainContentPanel.add(new HomePanel(), "Home");
        mainContentPanel.add(new BookManagementPanel(), "BookManagement");
        mainContentPanel.add(new InventoryManagementPanel(), "InventoryManagement");
        mainContentPanel.add(new CustomerManagementPanel(), "CustomerManagement");
        mainContentPanel.add(new OrderManagementPanel(), "OrderManagement");
        mainContentPanel.add(new UserManagementPanel(), "UserManagement");

        // 3. Gắn ActionListener cho các nút Sidebar
        btnHome.addActionListener(e -> cardLayout.show(mainContentPanel, "Home"));
        btnManagementBooks.addActionListener(e -> cardLayout.show(mainContentPanel, "BookManagement"));
        btnManagementInventory.addActionListener(e -> cardLayout.show(mainContentPanel, "InventoryManagement"));
        btnManagementCustomers.addActionListener(e -> cardLayout.show(mainContentPanel, "CustomerManagement"));
        btnManagementOrders.addActionListener(e -> cardLayout.show(mainContentPanel, "OrderManagement"));
        btnManagementUsers.addActionListener(e -> cardLayout.show(mainContentPanel, "UserManagement"));
        
        // 5. Hiển thị màn hình "Trang Chủ" mặc định khi khởi động
        cardLayout.show(mainContentPanel, "Home");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userInforPanel = new javax.swing.JPanel();
        lblWelcomeUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JToggleButton();
        sidebarPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JToggleButton();
        btnManagementBooks = new javax.swing.JToggleButton();
        btnManagementInventory = new javax.swing.JToggleButton();
        btnManagementCustomers = new javax.swing.JToggleButton();
        btnManagementOrders = new javax.swing.JToggleButton();
        btnManagementUsers = new javax.swing.JToggleButton();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOK MANAGEMENT");
        setAlwaysOnTop(true);

        headerPanel.setBackground(new java.awt.Color(0, 153, 204));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("BOOK MANAGEMENT");
        headerPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        userInforPanel.setOpaque(false);

        lblWelcomeUser.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblWelcomeUser.setText("Welcome: ");
        userInforPanel.add(lblWelcomeUser);

        btnLogout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        userInforPanel.add(btnLogout);

        headerPanel.add(userInforPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        sidebarPanel.setBackground(new java.awt.Color(204, 255, 255));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(250, 586));
        sidebarPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        btnHome.setBackground(new java.awt.Color(153, 204, 255));
        btnHome.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnHome.setForeground(new java.awt.Color(51, 51, 51));
        btnHome.setText("HOME");
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnHome);

        btnManagementBooks.setBackground(new java.awt.Color(153, 204, 255));
        btnManagementBooks.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnManagementBooks.setForeground(new java.awt.Color(51, 51, 51));
        btnManagementBooks.setText("BOOK MANAGEMENT");
        btnManagementBooks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnManagementBooks);

        btnManagementInventory.setBackground(new java.awt.Color(153, 204, 255));
        btnManagementInventory.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnManagementInventory.setForeground(new java.awt.Color(51, 51, 51));
        btnManagementInventory.setText("INVENTORY MANAGEMENT");
        btnManagementInventory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnManagementInventory);

        btnManagementCustomers.setBackground(new java.awt.Color(153, 204, 255));
        btnManagementCustomers.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnManagementCustomers.setForeground(new java.awt.Color(51, 51, 51));
        btnManagementCustomers.setText("CUSTOMER MANAGEMENT");
        btnManagementCustomers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnManagementCustomers);

        btnManagementOrders.setBackground(new java.awt.Color(153, 204, 255));
        btnManagementOrders.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnManagementOrders.setForeground(new java.awt.Color(51, 51, 51));
        btnManagementOrders.setText("ORDER MANAGEMENT");
        btnManagementOrders.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnManagementOrders);

        btnManagementUsers.setBackground(new java.awt.Color(153, 204, 255));
        btnManagementUsers.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnManagementUsers.setForeground(new java.awt.Color(51, 51, 51));
        btnManagementUsers.setText("USER MANAGEMENT");
        btnManagementUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sidebarPanel.add(btnManagementUsers);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        mainContentPanel.setBackground(new java.awt.Color(102, 102, 102));
        mainContentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        int confirm = JOptionPane.showConfirmDialog(this,
                                "Bạn có chắc chắn muốn đăng xuất?", "Xác nhận đăng xuất",
                                JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    dispose(); // Đóng cửa sổ MainFrame
                    login.setVisible(true);
                }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnHome;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JToggleButton btnManagementBooks;
    private javax.swing.JToggleButton btnManagementCustomers;
    private javax.swing.JToggleButton btnManagementInventory;
    private javax.swing.JToggleButton btnManagementOrders;
    private javax.swing.JToggleButton btnManagementUsers;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWelcomeUser;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel userInforPanel;
    // End of variables declaration//GEN-END:variables
}
