/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.bookmanagement.view;

/**
 *
 * @author ADMIN
 */

import com.bookmanagement.Dao.SettingDAO;
import com.bookmanagement.model.Order;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Hashtable;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.google.zxing.BarcodeFormat;

import com.google.zxing.EncodeHintType;

import com.google.zxing.MultiFormatWriter;

import com.google.zxing.WriterException;

import com.google.zxing.client.j2se.MatrixToImageWriter;

import com.google.zxing.common.BitMatrix;

public class PaymentDialog extends javax.swing.JDialog {

    /**
     * Creates new form PaymentDialog
     */
    
    private Order order;
    private BigDecimal actualAmount;
    private final SettingDAO settingDAO;

    
    public PaymentDialog(java.awt.Frame parent, boolean modal, Order order) {
         super(parent, modal);
        this.order = order;
        this.actualAmount = order.getActualAmount(); 
        this.settingDAO = new SettingDAO(); // Khởi tạo SettingDAO
        initComponents();
        setupPaymentDialog();
    }
    
    
    private void setupPaymentDialog() {
        lblOrderNumber.setText(String.valueOf(order.getOrderId()));
        
        // Định dạng số tiền để hiển thị đẹp hơn
        NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
        lblTotalAmount.setText(currencyFormatter.format(actualAmount));
        
        // Mặc định chọn thanh toán bằng chuyển khoản và tạo mã QR
        rbtnTransfer.setSelected(true);
        generateAndShowQRCode();
        
        // Thêm các listener cho các nút radio để chuyển đổi phương thức thanh toán
        rbtnTransfer.addActionListener(e -> generateAndShowQRCode());
        rbtnCash.addActionListener(e -> lblQRCode.setIcon(null));
    }
    
    /**
     * Tạo và hiển thị mã QR cho phương thức thanh toán chuyển khoản.
     */
    private void generateAndShowQRCode() {
        try {
            // Lấy thông tin ngân hàng từ database
            String bankName = settingDAO.getSetting("bank_name");
            String bankAccountNumber = settingDAO.getSetting("bank_account_number");

            if (bankName == null || bankAccountNumber == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin ngân hàng trong database.", "Lỗi Cấu Hình", JOptionPane.ERROR_MESSAGE);
                lblQRCode.setIcon(null);
                return;
            }

            // Dữ liệu cho mã QR
            String qrData = String.format(
                "Số tiền cần thanh toán: %s\nMã đơn hàng: %d\nNgân hàng: %s\nSố tài khoản: %s",
                actualAmount.toString(),
                order.getOrderId(),
                bankName,
                bankAccountNumber
            );
            
            // Tạo mã QR với kích thước 250x250
            BitMatrix matrix = new MultiFormatWriter().encode(
                qrData, 
                BarcodeFormat.QR_CODE, 250, 250, getHintMap());
            
            // Chuyển BitMatrix thành hình ảnh
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            MatrixToImageWriter.writeToStream(matrix, "PNG", baos);
            
            ImageIcon qrCodeIcon = new ImageIcon(baos.toByteArray());
            // Đặt hình ảnh mã QR vào JLabel và căn giữa
            lblQRCode.setIcon(qrCodeIcon);
            lblQRCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        } catch (WriterException | IOException ex) {
            Logger.getLogger(PaymentDialog.class.getName()).log(Level.SEVERE, "Lỗi khi tạo mã QR", ex);
            JOptionPane.showMessageDialog(this, "Không thể tạo mã QR. Vui lòng thử lại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private Hashtable getHintMap() {
        Hashtable<EncodeHintType, String> hintMap = new Hashtable<>();
        hintMap.put(EncodeHintType.CHARACTER_SET, "UTF-8");
        return hintMap;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPaymentMethod = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblOrderNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        rbtnCash = new javax.swing.JRadioButton();
        rbtnTransfer = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lblQRCode = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Order: ");

        lblOrderNumber.setText("#");

        jLabel2.setText("Total: ");

        lblTotalAmount.setText("0 VND");

        btgPaymentMethod.add(rbtnCash);
        rbtnCash.setText("CASH");

        btgPaymentMethod.add(rbtnTransfer);
        rbtnTransfer.setText("TRANSFER");

        jLabel3.setText("Select payment method: ");

        lblQRCode.setBackground(new java.awt.Color(102, 102, 102));
        lblQRCode.setForeground(new java.awt.Color(255, 255, 255));
        lblQRCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQRCode.setText("QR CODE");
        lblQRCode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnPrint.setText("PRINT");

        btnCancel.setText("CANCEL");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("PAYMENT ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnCash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(jLabel4)))
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addGap(102, 102, 102)
                .addComponent(btnCancel)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblOrderNumber))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalAmount))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(rbtnCash)
                .addGap(27, 27, 27)
                .addComponent(rbtnTransfer)
                .addGap(34, 34, 34)
                .addComponent(lblQRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnCancel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPaymentMethod;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblQRCode;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JRadioButton rbtnCash;
    private javax.swing.JRadioButton rbtnTransfer;
    // End of variables declaration//GEN-END:variables
}
